version: '3.9'
services:
  email_backend: 
    build: .
    volumes:
      - .:/app

  mailhog: 
    image: mailhog/mailhog:latest 
    restart: always 
    ports: 
      - 1025:1025 
      - 8025:8025 

